# Usa un'immagine base di Windows Server Core con Node.js LTS preinstallato
FROM mcr.microsoft.com/windows/servercore:ltsc2019-amd64

# Imposta la directory di lavoro all'interno del container
WORKDIR C:\app

# Copia i file package.json e package-lock.json per installare le dipendenze
COPY package*.json ./

# Installa le dipendenze di Node.js e il pacchetto 'serve' per servire i file statici
RUN powershell -Command npm install && npm install -g serve

# Copia il resto del codice sorgente dell'applicazione
COPY . .

# Costruisci l'applicazione React
RUN powershell -Command npm run build

# Espone la porta su cui il frontend sarà servito (di solito 3000 per lo sviluppo, 80 o 5000 per la produzione)
EXPOSE 3000

# Comando per avviare il server statico per i file di build
CMD [ "serve", "-s", "build", "-l", "3000" ]
